version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    hostname: zuggerlner
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
